#!/usr/bin/env bash
#
# ▞▀▖▞▀▖                    ▗▀▖   ▐     ▌
#  ▗▘▌▞▌  ▞▀▘▞▀▖▙▀▖▞▀▖▞▀▖▛▀▖▐  ▞▀▖▜▀ ▞▀▖▛▀▖
# ▗▘ ▛ ▌  ▝▀▖▌ ▖▌  ▛▀ ▛▀ ▌ ▌▜▀ ▛▀ ▐ ▖▌ ▖▌ ▌
# ▀▀▘▝▀▀▀▀▀▀ ▝▀ ▘  ▝▀▘▝▀▘▘ ▘▐  ▝▀▘ ▀ ▝▀ ▘ ▘
#   https://github.com/KittyKatt/screenFetch

if hash screenfetch 2> /dev/null; then
    screenfetch -E
fi
