#!/usr/bin/env bash
#░████████████████████████████████████████████████████████████████████████████░#
#░█                                                                          █░#
#░█     ████                            ██   ██                              █░#
#░█    ░██░                            ░██  ░░                               █░#
#░█   ██████ ██   ██ ███████   █████  ██████ ██  ██████  ███████   ██████    █░#
#░█  ░░░██░ ░██  ░██░░██░░░██ ██░░░██░░░██░ ░██ ██░░░░██░░██░░░██ ██░░░░     █░#
#░█    ░██  ░██  ░██ ░██  ░██░██  ░░   ░██  ░██░██   ░██ ░██  ░██░░█████     █░#
#░█    ░██  ░██  ░██ ░██  ░██░██   ██  ░██  ░██░██   ░██ ░██  ░██ ░░░░░██    █░#
#░█    ░██  ░░██████ ███  ░██░░█████   ░░██ ░██░░██████  ███  ░██ ██████     █░#
#░█    ░░    ░░░░░░ ░░░   ░░  ░░░░░     ░░  ░░  ░░░░░░  ░░░   ░░ ░░░░░░      █░#
#░█                                                                          █░#
#░████████████████████████████████████████████████████████████████████████████░#

#░█ base64 encode 
e64() {
  base64 -b0 <<< "$1"
}

#░█ base64 decode
d64() {
  base64 -D <<< "$1"
}

#░█  current script's directory
script_dir() {
  local src dir

  src="${BASH_SOURCE[0]}"
  while [ -h "$src" ]; do
    dir="$( cd -P "$( dirname "$src" )" && pwd )"
    src="$( readlink "$src" )"
    [[ $src != /* ]] && src="$dir/$src"
  done
  dir="$( cd -P "$( dirname "$src" )" && pwd )"
  echo "$dir"
}

#░█  pipe things to atom (this sucks)
atom_pipe() {
  ATOM_TEMP=$(mktemp /tmp/atom.XXXX)
  cat > $ATOM_TEMP
  atom -a --wait $ATOM_TEMP
  rm $ATOM_TEMP
}

#░█  all the laziness
q() {
  mysql -u root $1 -e "$2"
}
