#!/usr/bin/env bash
#░█                      ██
#░█            ██████   ░██
#░█    ██████ ░██░░░██ ██████  ██████
#░█   ██░░░░██░██  ░██░░░██░  ██░░░░
#░█  ░██   ░██░██████   ░██  ░░█████
#░█  ░██   ░██░██░░░    ░██   ░░░░░██
#░█  ░░██████ ░██       ░░██  ██████
#░█   ░░░░░░  ░░         ░░  ░░░░░░

shopt -s checkwinsize
shopt -s globstar
shopt -s cmdhist
shopt -s histappend
shopt -s cmdhist

VISUAL=vim
EDITOR="$VISUAL"

PATH="$HOME/bin:$HOME/.local/bin:$PATH"
