#!/usr/bin/env bash
#░████████████████████████████████████████████████████████████████████████████░#
#░█                                                                          █░#
#░█                                                         ██               █░#
#░█           ██████                              ██████   ░██               █░#
#░█          ░██░░░██ ██████  ██████  ██████████ ░██░░░██ ██████             █░#
#░█          ░██  ░██░░██░░█ ██░░░░██░░██░░██░░██░██  ░██░░░██░              █░#
#░█          ░██████  ░██ ░ ░██   ░██ ░██ ░██ ░██░██████   ░██               █░#
#░█          ░██░░░   ░██   ░██   ░██ ░██ ░██ ░██░██░░░    ░██               █░#
#░█          ░██     ░███   ░░██████  ███ ░██ ░██░██       ░░██              █░#
#░█          ░░      ░░░     ░░░░░░  ░░░  ░░  ░░ ░░         ░░               █░#
#░█                                                                          █░#
#░████████████████████████████████████████████████████████████████████████████░#

GIT_PS1_HIDE_IF_PWD_IGNORED=1
GIT_PS1_SHOWUPSTREAM=auto
GIT_PS1_SHOWDIRTYSTATE=1
GIT_PS1_SHOWCOLORHINTS=1
GIT_PS1_SHOWUNTRACKEDFILES=1

PROMPT_COMMAND='history -a; hist import > /dev/null;'

if hash git 2> /dev/null; then
  source ~/.config/dotfiles/git-completion.sh
  source ~/.config/dotfiles/git-prompt.sh

  _ps1_suffix='\\\$ '
  _ps1_prefix='\u@\h:\w'

  PROMPT_COMMAND+="__git_ps1 \"${_ps1_prefix}\" \"${_ps1_suffix}\""

  unset _ps1_prefix _ps1_suffix
fi
