#!/usr/bin/env bash
#░█                       ██
#░█                      ░██
#░█   ███     ██  ██████ ░██
#░█  ░░██  █ ░██ ██░░░░  ░██
#░█   ░██ ███░██░░█████  ░██
#░█   ░████░████ ░░░░░██ ░██
#░█   ███░ ░░░██ ██████  ███
#░█  ░░░    ░░░ ░░░░░░  ░░░
#░█   https://docs.microsoft.com/en-us/windows/wsl/about

if [[ -f /proc/version && $(</proc/version) == *Microsoft@Microsoft* ]]; then
	# Set correct umask
	# Microsoft/BashOnWindows#352
	if [[ "$(umask)" == '0000' ]]; then
		umask 022
	fi
fi
