#!/usr/bin/env bash
#░█   ██
#░█  ░██
#░█  ░██      ██████  █████  ███     ██
#░█  ░██████ ░░██░░█ ██░░░██░░██  █ ░██
#░█  ░██░░░██ ░██ ░ ░███████ ░██ ███░██
#░█  ░██  ░██ ░██   ░██░░░░  ░████░████
#░█  ░██████ ░███   ░░██████ ███░ ░░░██
#░█  ░░░░░   ░░░     ░░░░░░ ░░░    ░░░
#░█    https://brew.sh/

if hash brew 2> /dev/null; then
  export BASH_COMPLETION_COMPAT_DIR="/usr/local/etc/bash_completion.d"
  [[ -r "/usr/local/etc/profile.d/bash_completion.sh" ]] && . "/usr/local/etc/profile.d/bash_completion.sh"

  unset brew_prefix completion_file
fi

