#!/usr/bin/env bash
#░█    █████                   ██████   █████
#░█   ██░░░██ ███████  ██   ██░██░░░██ ██░░░██
#░█  ░██  ░██░░██░░░██░██  ░██░██  ░██░██  ░██
#░█  ░░██████ ░██  ░██░██  ░██░██████ ░░██████
#░█   ░░░░░██ ░██  ░██░██  ░██░██░░░   ░░░░░██
#░█    █████  ███  ░██░░██████░██       █████
#░█   ░░░░░  ░░░   ░░  ░░░░░░ ░░       ░░░░░

if hash gpg 2> /dev/null || hash gpg2 2> /dev/null; then
  if [[ -r ~/.gnupg/.gpg-agent-info ]] && [[ -n $(pgrep gpg-agent) ]]; then
      source ~/.gnupg/.gpg-agent-info
  else
      gpg-agent --daemon
  fi

  export GPG_AGENT_INFO
fi
