#!/usr/bin/env bash
#░█   ██████   ██   ██
#░█  ░██░░░██ ░░██ ██   █████  ███████  ██    ██
#░█  ░██  ░██  ░░███   ██░░░██░░██░░░██░██   ░██
#░█  ░██████    ░██   ░███████ ░██  ░██░░██ ░██
#░█  ░██░░░     ██    ░██░░░░  ░██  ░██ ░░████
#░█  ░██       ██     ░░██████ ███  ░██  ░░██
#░█  ░░       ░░       ░░░░░░ ░░░   ░░    ░░
#░█    https://github.com/pyenv/pyenv
#░█    https://github.com/pyenv/pyenv-virtualenv

if hash pyenv 2> /dev/null; then
  eval "$(pyenv init -)"

  if hash pyenv-virtualenv 2> /dev/null; then
    eval "$(pyenv virtualenv-init -)"
  fi
fi

