#!/usr/bin/env bash
shopt -s checkwinsize
shopt -s globstar
shopt -s cmdhist
shopt -s histappend
shopt -s cmdhist

HISTFILESIZE=1000000
HISTSIZE=1000000
HISTCONTROL=ignoreboth
HISTIGNORE='ls:bg:fg:history'
HISTTIMEFORMAT='%F %T '

VISUAL=vim
EDITOR="$VISUAL"

PATH="$HOME/bin:$HOME/.local/bin:$PATH"
