#!/usr/bin/env bash
#░█     ████ ██          ██           ██
#░█    ░██░ ░░   █████  ░██          ░██
#░█   ██████ ██ ██░░░██ ░██  █████  ██████
#░█  ░░░██░ ░██░██  ░██ ░██ ██░░░██░░░██░
#░█    ░██  ░██░░██████ ░██░███████  ░██
#░█    ░██  ░██ ░░░░░██ ░██░██░░░░   ░██
#░█    ░██  ░██  █████  ███░░██████  ░░██
#░█    ░░   ░░  ░░░░░  ░░░  ░░░░░░    ░░

_figlet_suffix() {
  case $(uname -s) in
    Darwin)
      echo '| tee >(pbcopy)' ;;
  esac
}

if ! hash figlet 2> /dev/null; then
  echo "ERR: figlet not installed"  && return 0
fi

3d() {
  eval "figlet -d ~/.figlet_fonts -f 3d $@ $(_figlet_suffix)"
}

smblock() {
  eval "figlet -d ~/.figlet_fonts -f smblock '$@' $(_figlet_suffix)"
}