#!/usr/bin/env bash
#
# ▞▀▖▞▀▖  ▌  ▞▀▖
#  ▗▘▌▞▌  ▌▗▘▚▄▘▞▀▘
# ▗▘ ▛ ▌  ▛▚ ▌ ▌▝▀▖
# ▀▀▘▝▀▀▀▀▘ ▘▝▀ ▀▀
#   https://kubernetes.io/docs/home/

export K8_HOME="$HOME/.kubeenv"

export K8_ENV
export KUBECONFIG

# Tab completion for k8 and k8_rm.
function _kubeenv()
{
    local cur opts
    cur="${COMP_WORDS[COMP_CWORD]}"
    opts="$(ls "$K8_HOME")"

    COMPREPLY=($(compgen -W "${opts}" -- ${cur}))
    return 0
}
complete -o default -F _kubeenv k8 k8_rm

function k8() {
    if [[ $# != 1 ]]; then
        echo "Usage: k8 [K8_ENV]" >&2
        return 2
    fi

    if [[ -n $K8_ENV ]]; then k8_disable; fi

    K8_ENV="$1"
    export K8_ENV

    if [[ ! -d $K8_HOME ]]; then mkdir -p $K8_HOME; fi
    touch "$K8_HOME/$K8_ENV"

    KUBECONFIG="$K8_HOME/$K8_ENV"
    export KUBECONFIG
}

function k8_disable() {
    unset KUBECONFIG
    unset K8_ENV
}

function k8_rm() {
    if [[ $# != 1 ]]; then
        echo "Usage: k8_rm NAME" >&2
        return 2
    fi

    if [[ $K8_ENV = $1 ]]; then
        echo "Can't delete active kubeenv. Run k8_disable before" >&2
        return 2
    fi

    if [[ ! -e $K8_HOME/$1 ]]; then
        echo "k8 env $1 doesn't exist" >&2
        return 2
    fi

    rm -f "$K8_HOME/$1"
}
